import { spawn } from 'child_process';
import { mkdtemp, readFile, rm, stat } from 'fs/promises';
import { tmpdir } from 'os';
import { join } from 'path';
import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { pathPriority, TEXT_FILE_RE } from './scan-pipeline.service';
import {
  SECRET_GREP_ANCHORS,
  PRIVATE_KEY_ANCHORS,
  FullRepoSecretCandidate,
} from '../detection/rules/secrets.rule';
import { SAFE_BRANCH_RE } from './branch-name.util';
import { hasWordBoundaryMatch } from '../common/utils/word-match.util';

/**
 * Directories never worth walking into: dependency trees, build output, VCS
 * internals. Skipping these outright is what makes a full-repo clone+scan
 * viable instead of grinding through thousands of irrelevant files.
 */
export const EXCLUDED_DIRS = new Set([
  '.git',
  'node_modules',
  'vendor',
  'dist',
  'build',
  'out',
  '.next',
  'target',
  'venv',
  '.venv',
  '__pycache__',
  'coverage',
  '.cache',
  'bower_components',
  '.gradle',
  '.idea',
  '.vscode',
]);

export interface BrandTextMatch {
  alias: string;
  path: string;
  lineNumber: number;
  line: string;
}

export interface CloneScanResult {
  filePaths: string[];
  readmeText: string;
  /** Actual repo-relative path of the README that was read into `readmeText` (case/extension varies per repo), so findings can link to a real file instead of a literal "readme". */
  readmePath?: string;
  smallFileTexts: Array<{ path: string; content: string }>;
  /**
   * Every line across the WHOLE repo tree that contains a brand alias,
   * found via `git grep` rather than the maxFiles-capped `smallFileTexts`
   * selection above - so a brand mention in file #4000 of a huge repo is
   * just as findable as one in file #1.
   */
  brandMatches: BrandTextMatch[];
  /** Same full-repo depth as brandMatches, but for the brand's own curated keywords. */
  keywordMatches: BrandTextMatch[];
  /** Raw (unverified) full-repo hits on literal secret-pattern anchors - see secrets.rule.ts's findFullRepoSecretMatches for the regex re-verification step. */
  secretCandidates: FullRepoSecretCandidate[];
}

/**
 * Sanity ceiling on how many custom keywords get combined into one grep
 * call - a scan spanning many keyword-heavy brands (60+ keywords each)
 * could otherwise build an unreasonably long pattern list for a single
 * repo's grep pass. Not expected to bind in normal single-brand scans.
 */
const MAX_KEYWORDS_FOR_CLONE_GREP = 200;

export function isExcludedPath(path: string): boolean {
  return path.split('/').some((segment) => EXCLUDED_DIRS.has(segment));
}

/**
 * Lockfiles auto-generated by a package manager - never hand-authored, and
 * exactly the kind of huge, base64-dense file that (a) makes a multi-pattern
 * grep pass slow for no benefit and (b) coincidentally contains substrings
 * that look like a secret-pattern anchor purely by chance (an npm integrity
 * hash matching "eyJ" or similar - a real false positive seen in this exact
 * codebase during testing, not a hypothetical).
 */
const GREP_EXCLUDE_FILES = [
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'composer.lock',
  'Gemfile.lock',
  'poetry.lock',
  'Cargo.lock',
  'Pipfile.lock',
];

/** `git grep` pathspecs that skip the same noisy dirs/files a clone-based scan already excludes from selection. */
const GREP_EXCLUDE_PATHSPECS = [
  ...Array.from(EXCLUDED_DIRS, (d) => `:(glob,exclude)**/${d}/**`),
  ...GREP_EXCLUDE_FILES.map((f) => `:(glob,exclude)**/${f}`),
];

function basename(path: string): string {
  const idx = path.lastIndexOf('/');
  return idx === -1 ? path : path.slice(idx + 1);
}

export interface RemoteHead {
  sha: string;
  defaultBranch?: string;
}

/**
 * Parses `git ls-remote --symref <url> HEAD` output, e.g.:
 *   ref: refs/heads/main	HEAD
 *   3f2504e0...c3a1	HEAD
 * Exported standalone so parsing logic can be unit tested without spawning
 * a real git process.
 */
export function parseLsRemoteHead(stdout: string): RemoteHead | null {
  let defaultBranch: string | undefined;
  let sha: string | undefined;
  for (const rawLine of stdout.split('\n')) {
    const line = rawLine.trim();
    if (!line) continue;
    if (line.startsWith('ref:')) {
      const match = /ref:\s+refs\/heads\/(\S+)/.exec(line);
      if (match) defaultBranch = match[1];
      continue;
    }
    const [maybeSha, ref] = line.split(/\s+/);
    if (ref === 'HEAD' && /^[0-9a-f]{40}$/i.test(maybeSha)) {
      sha = maybeSha;
    }
  }
  return sha ? { sha, defaultBranch } : null;
}

/**
 * Alternative to per-file REST content fetching: shallow-clones a public repo
 * over git's own transport (no GitHub REST rate limit involved at all) and
 * scans the full working tree locally. Opt-in via ENABLE_CLONE_SCAN, and
 * fails closed — any error here just returns null so the caller falls back
 * to the existing REST-based fetch instead of breaking the scan.
 */
@Injectable()
export class CloneScanService {
  private readonly logger = new Logger(CloneScanService.name);
  private gitAvailable: boolean | null = null;

  constructor(private readonly config: ConfigService) {}

  isEnabled(): boolean {
    // Default-on: bypasses the GitHub REST client (and all of its Redis
    // rate-limit/concurrency bookkeeping) entirely for eligible repos, which
    // is what keeps a large scan from burning through a metered Redis
    // plan's command budget. Fails closed either way, so an explicit
    // `false` (or a missing git binary at runtime) just falls back to the
    // existing REST-based fetch with no behavior change.
    const raw = this.config.get<string>('ENABLE_CLONE_SCAN');
    return raw === undefined || raw.toLowerCase() !== 'false';
  }

  async shouldAttempt(sizeKb: number | undefined): Promise<boolean> {
    if (!this.isEnabled()) return false;
    // Unknown size (e.g. resumed jobs that never captured it, or - the
    // common case - repos discovered via code search: GitHub's
    // /search/code response's nested `repository` object has no `size`
    // field at all, see github.service.ts's searchCode mapping) used to
    // skip straight to the 12-file REST fallback here, which meant every
    // code-search hit - the discovery family most likely to bury a brand
    // mention in file content rather than repo name/description - never
    // got full-repo coverage. Attempt the clone instead: it's bounded by
    // CLONE_SCAN_TIMEOUT_MS and fails closed to the REST fallback on any
    // error/timeout either way, same safety net as a known-oversized repo.
    const maxKb = Number(
      this.config.get('CLONE_SCAN_MAX_REPO_SIZE_KB') || 51200,
    );
    if (sizeKb !== undefined && sizeKb > maxKb) return false;
    return this.checkGitAvailable();
  }

  /**
   * A plain `--depth 1` shallow clone, not a partial (`--filter=blob:none
   * --no-checkout`) one - the working tree is fully materialized as soon as
   * clone finishes, no separate checkout step needed. This used to be a
   * partial clone with a selective lazy checkout of just the files worth
   * reading (cheaper on bandwidth), but `git checkout` does not reliably
   * trigger the promisor remote's lazy blob fetch on every git version -
   * confirmed failing 100% of the time on this deployment's git (2.39.1):
   * checkout errors "unable to read sha1 file" for every path, even though
   * the exact same blob fetches fine via an explicit `git fetch <oid>`. A
   * full shallow clone has no such lazy-fetch step to fail, at the cost of
   * transferring the whole repo tree at HEAD instead of a handful of files -
   * bounded by the existing CLONE_SCAN_MAX_REPO_SIZE_KB cap either way.
   */
  async cloneAndScan(
    owner: string,
    name: string,
    brandAliases: string[] = [],
    options: { customKeywords?: string[]; branch?: string } = {},
  ): Promise<CloneScanResult | null> {
    const timeoutMs = Number(
      this.config.get('CLONE_SCAN_TIMEOUT_MS') || 30_000,
    );
    const maxFiles = Number(this.config.get('CLONE_SCAN_MAX_FILES') || 200);
    const maxFileBytes = Number(
      this.config.get('GITHUB_MAX_FILE_BYTES') || 51200,
    );

    let dir: string | null = null;
    try {
      dir = await mkdtemp(join(tmpdir(), 'osint-clone-'));
      const url = `https://github.com/${owner}/${name}.git`;
      await this.runGitClone(url, dir, timeoutMs, options.branch);

      const filePaths = (await this.runGitLsTree(dir, timeoutMs)).filter(
        (p) => !isExcludedPath(p),
      );

      const ranked = filePaths
        .map((p) => ({ path: p, score: pathPriority(p, brandAliases) }))
        .filter((p) => p.score > 0 && TEXT_FILE_RE.test(p.path))
        .sort((a, b) => b.score - a.score || a.path.localeCompare(b.path));

      const selected: string[] = [];
      for (const entry of ranked) {
        if (selected.length >= maxFiles) break;
        selected.push(entry.path);
      }
      if (selected.length < maxFiles) {
        for (const p of filePaths) {
          if (selected.length >= maxFiles) break;
          if (selected.includes(p)) continue;
          if (!TEXT_FILE_RE.test(p)) continue;
          selected.push(p);
        }
      }

      const readmePath = filePaths.find((p) =>
        /^readme(\.[a-z0-9]+)?$/i.test(basename(p)),
      );

      const smallFileTexts: Array<{ path: string; content: string }> = [];
      for (const relPath of selected) {
        const content = await this.readFileCapped(
          join(dir, relPath),
          maxFileBytes,
        );
        if (content !== null) smallFileTexts.push({ path: relPath, content });
      }

      const readmeText = readmePath
        ? (await this.readFileCapped(join(dir, readmePath), maxFileBytes)) || ''
        : '';

      const brandMatches = await this.grepBrandMentions(
        dir,
        brandAliases,
        Number(this.config.get('CLONE_SCAN_GREP_TIMEOUT_MS') || 60_000),
      );
      const keywordMatches = await this.grepCustomKeywords(
        dir,
        (options.customKeywords || []).slice(0, MAX_KEYWORDS_FOR_CLONE_GREP),
        Number(this.config.get('CLONE_SCAN_KEYWORD_GREP_TIMEOUT_MS') || 30_000),
      );
      const secretCandidates = await this.grepSecretAnchors(
        dir,
        Number(this.config.get('CLONE_SCAN_SECRET_GREP_TIMEOUT_MS') || 30_000),
      );

      return {
        filePaths,
        readmeText,
        readmePath,
        smallFileTexts,
        brandMatches,
        keywordMatches,
        secretCandidates,
      };
    } catch (error) {
      this.logger.warn(
        `Clone-based scan failed for ${owner}/${name}${options.branch ? `@${options.branch}` : ''}: ${(error as Error).message}`,
      );
      return null;
    } finally {
      if (dir) {
        await this.cleanupCloneDir(dir);
      }
    }
  }

  /**
   * A cloned repo's directory is meant to be deleted the instant a scan is
   * done with it - if that silently fails, the (often hundreds-of-MB)
   * checkout just sits in the OS temp dir forever, invisibly eating disk.
   * On Windows in particular, killing a still-running `git` process with
   * SIGKILL (see runGitClone's timeout) doesn't guarantee its file handles
   * are released the instant `kill()` returns - deleting immediately after
   * can lose a race against that teardown and fail with EBUSY/EPERM.
   * `maxRetries`/`retryDelay` make Node's own `rm` retry past exactly that
   * transient window; logging on final failure (instead of the previous
   * silent swallow) means a genuinely stuck clone is at least visible.
   */
  private async cleanupCloneDir(dir: string): Promise<void> {
    try {
      await rm(dir, {
        recursive: true,
        force: true,
        maxRetries: 5,
        retryDelay: 300,
      });
    } catch (error) {
      this.logger.warn(
        `Failed to remove clone temp dir ${dir}: ${(error as Error).message}`,
      );
    }
  }

  /**
   * Current HEAD commit SHA + default branch over git's own transport - no
   * GitHub REST call at all (the REST equivalent, getRepositoryHead, is
   * actually *two* REST calls: repo metadata, then the branch ref). Used to
   * make the incremental "did this change" decision for clone-eligible
   * repos without spending any GitHub quota or Redis rate-limit bookkeeping
   * on it. Fails closed - null on any error, letting the caller fall back
   * to the REST-based check exactly as before.
   */
  async getRemoteHead(owner: string, name: string): Promise<RemoteHead | null> {
    if (!(await this.checkGitAvailable())) return null;
    const timeoutMs = Number(
      this.config.get('CLONE_SCAN_TIMEOUT_MS') || 30_000,
    );
    const url = `https://github.com/${owner}/${name}.git`;
    try {
      return await this.runGitLsRemote(url, timeoutMs);
    } catch (error) {
      this.logger.warn(
        `git ls-remote failed for ${owner}/${name}: ${(error as Error).message}`,
      );
      return null;
    }
  }

  private runGitLsRemote(
    url: string,
    timeoutMs: number,
  ): Promise<RemoteHead | null> {
    return new Promise((resolve, reject) => {
      const proc = spawn('git', ['ls-remote', '--symref', url, 'HEAD']);
      let stdout = '';
      proc.stdout?.on('data', (chunk: Buffer) => {
        stdout += chunk.toString('utf8');
      });
      const timer = setTimeout(() => {
        proc.kill('SIGKILL');
        reject(new Error(`git ls-remote timed out after ${timeoutMs}ms`));
      }, timeoutMs);
      proc.on('error', (err) => {
        clearTimeout(timer);
        reject(err);
      });
      proc.on('exit', (code) => {
        clearTimeout(timer);
        if (code !== 0) {
          reject(new Error(`git ls-remote exited with code ${code}`));
          return;
        }
        resolve(parseLsRemoteHead(stdout));
      });
    });
  }

  private async checkGitAvailable(): Promise<boolean> {
    if (this.gitAvailable !== null) return this.gitAvailable;
    this.gitAvailable = await new Promise<boolean>((resolve) => {
      try {
        const proc = spawn('git', ['--version']);
        proc.on('error', () => resolve(false));
        proc.on('exit', (code) => resolve(code === 0));
      } catch {
        resolve(false);
      }
    });
    if (!this.gitAvailable) {
      this.logger.warn(
        'git binary not found - clone-based scanning disabled, falling back to REST file fetch',
      );
    }
    return this.gitAvailable;
  }

  private runGitClone(
    url: string,
    dir: string,
    timeoutMs: number,
    branch?: string,
  ): Promise<void> {
    return new Promise((resolve, reject) => {
      const args = ['clone', '--depth', '1', '--single-branch', '--no-tags'];
      if (branch) {
        // Defense in depth against argument injection - a branch name
        // starting with "-" would otherwise be parsed by git as a flag
        // (e.g. an "--upload-pack=..." style option), not a ref, even
        // though spawn's argv array already rules out shell injection.
        // Real branch names never look like this, so rejecting it here
        // costs nothing legitimate. assertSafeBranchName (the controller-
        // level guard) already validates this before it gets this far -
        // this is a second, cheap check at the actual exec boundary.
        if (!SAFE_BRANCH_RE.test(branch)) {
          reject(new Error(`Refusing to clone unsafe branch name: ${branch}`));
          return;
        }
        args.push('--branch', branch);
      }
      args.push(url, dir);
      const proc = spawn('git', args, { stdio: 'ignore' });
      const timer = setTimeout(() => {
        proc.kill('SIGKILL');
        reject(new Error(`git clone timed out after ${timeoutMs}ms`));
      }, timeoutMs);
      proc.on('error', (err) => {
        clearTimeout(timer);
        reject(err);
      });
      proc.on('exit', (code) => {
        clearTimeout(timer);
        if (code === 0) resolve();
        else reject(new Error(`git clone exited with code ${code}`));
      });
    });
  }

  /** Lists every file in HEAD's tree (already present on disk from the clone). */
  private runGitLsTree(dir: string, timeoutMs: number): Promise<string[]> {
    return new Promise((resolve, reject) => {
      const proc = spawn('git', [
        '-C',
        dir,
        'ls-tree',
        '-r',
        '-z',
        '--name-only',
        'HEAD',
      ]);
      const chunks: Buffer[] = [];
      proc.stdout?.on('data', (chunk: Buffer) => chunks.push(chunk));
      const timer = setTimeout(() => {
        proc.kill('SIGKILL');
        reject(new Error(`git ls-tree timed out after ${timeoutMs}ms`));
      }, timeoutMs);
      proc.on('error', (err) => {
        clearTimeout(timer);
        reject(err);
      });
      proc.on('exit', (code) => {
        clearTimeout(timer);
        if (code !== 0) {
          reject(new Error(`git ls-tree exited with code ${code}`));
          return;
        }
        // NUL-separated (-z) so filenames with spaces/unicode never need
        // quote-escaping to be parsed correctly.
        const paths = Buffer.concat(chunks)
          .toString('utf8')
          .split('\0')
          .map((p) => p.trim())
          .filter(Boolean);
        resolve(paths);
      });
    });
  }

  /**
   * Full-repo, line-by-line search for the brand's name/aliases via `git
   * grep` on the tree that's already cloned locally - not limited to the
   * same maxFiles-capped selection used for secret-scanning. One `-F`
   * (literal, not regex) case-insensitive pass per alias; `-I` skips binary
   * files automatically. Fails closed per-alias: one alias erroring (e.g. an
   * unusual character git's CLI trips on) doesn't lose matches for the rest.
   */
  private async grepBrandMentions(
    dir: string,
    brandAliases: string[],
    timeoutMs: number,
  ): Promise<BrandTextMatch[]> {
    const raw = this.config.get<string>('ENABLE_DEEP_BRAND_GREP');
    if (raw !== undefined && raw.toLowerCase() === 'false') return [];

    const aliases = [
      ...new Set(brandAliases.filter((a) => a && a.trim().length >= 3)),
    ];
    if (aliases.length === 0) return [];

    const results: BrandTextMatch[] = [];
    const seen = new Set<string>();
    for (const alias of aliases) {
      let hits: Array<{ path: string; lineNumber: number; line: string }>;
      try {
        hits = await this.runGitGrep(dir, alias, timeoutMs);
      } catch (error) {
        this.logger.warn(
          `git grep failed for alias "${alias}": ${(error as Error).message}`,
        );
        continue;
      }
      for (const h of hits) {
        if (isExcludedPath(h.path)) continue;
        // `git grep -F` is a plain fixed-string search - it has no concept
        // of word boundaries, so it happily reports "fyers" appearing mid-
        // word inside "identifyers"/"modifyers" as a hit. Re-verify the
        // actual line text here before trusting it; see word-match.util.ts
        // for exactly what counts as a genuine boundary (camelCase/
        // snake_case/path-separated compounds still count, only a buried
        // run of letters inside an unrelated word is rejected).
        if (!hasWordBoundaryMatch(h.line, alias.toLowerCase())) continue;
        const key = `${h.path}:${h.lineNumber}`;
        if (seen.has(key)) continue;
        seen.add(key);
        results.push({ alias, ...h });
      }
    }
    return results;
  }

  /** `git grep -n <pattern> HEAD` on a treeish - no worktree checkout required, lazily fetches only the blobs it actually needs to search. */
  private runGitGrep(
    dir: string,
    pattern: string,
    timeoutMs: number,
  ): Promise<Array<{ path: string; lineNumber: number; line: string }>> {
    return new Promise((resolve, reject) => {
      const proc = spawn('git', [
        '-C',
        dir,
        'grep',
        '-n',
        '-i',
        '-I',
        '-F',
        '-e',
        pattern,
        'HEAD',
        '--',
        '.',
        ...GREP_EXCLUDE_PATHSPECS,
      ]);
      const chunks: Buffer[] = [];
      proc.stdout?.on('data', (chunk: Buffer) => chunks.push(chunk));
      const timer = setTimeout(() => {
        proc.kill('SIGKILL');
        reject(new Error(`git grep timed out after ${timeoutMs}ms`));
      }, timeoutMs);
      proc.on('error', (err) => {
        clearTimeout(timer);
        reject(err);
      });
      proc.on('exit', (code) => {
        clearTimeout(timer);
        // Exit code 1 means "ran fine, no matches" for git grep - not an error.
        if (code !== 0 && code !== 1) {
          reject(new Error(`git grep exited with code ${code}`));
          return;
        }
        const out = Buffer.concat(chunks).toString('utf8');
        const results: Array<{
          path: string;
          lineNumber: number;
          line: string;
        }> = [];
        for (const rawLine of out.split('\n')) {
          if (!rawLine) continue;
          const match = /^HEAD:(.+?):(\d+):(.*)$/.exec(rawLine);
          if (!match) continue;
          results.push({
            path: match[1],
            lineNumber: Number(match[2]),
            line: match[3].trim().slice(0, 300),
          });
        }
        resolve(results);
      });
    });
  }

  /**
   * Full-repo search for this brand's own curated keywords, same depth as
   * grepBrandMentions but a single combined `git grep` call (multiple `-e`
   * patterns ORed together) instead of one call per term - keyword lists can
   * run into the dozens, and looping one grep process per term the way
   * grepBrandMentions does (fine for 1-3 aliases) would not scale to that.
   * Since one grep call can't say *which* pattern matched a given line, each
   * hit is re-checked in JS against every keyword to attribute it correctly.
   */
  private async grepCustomKeywords(
    dir: string,
    keywords: string[],
    timeoutMs: number,
  ): Promise<BrandTextMatch[]> {
    const raw = this.config.get<string>('ENABLE_DEEP_KEYWORD_GREP');
    if (raw !== undefined && raw.toLowerCase() === 'false') return [];

    const terms = [
      ...new Set(keywords.map((k) => k.trim()).filter((k) => k.length >= 2)),
    ];
    if (terms.length === 0) return [];

    let hits: Array<{ path: string; lineNumber: number; line: string }>;
    try {
      hits = await this.runGitGrepMulti(dir, terms, timeoutMs);
    } catch (error) {
      this.logger.warn(
        `git grep failed for custom keywords: ${(error as Error).message}`,
      );
      return [];
    }

    const lowerTerms = terms.map((t) => t.toLowerCase());
    const results: BrandTextMatch[] = [];
    const seen = new Set<string>();
    for (const h of hits) {
      if (isExcludedPath(h.path)) continue;
      for (let i = 0; i < terms.length; i++) {
        // Same re-verification as grepBrandMentions above - the combined
        // grep call here is also a plain fixed-string search, so a hit for
        // ANY of the ORed keywords still needs each candidate keyword
        // checked against a real word boundary before it's attributed.
        if (!hasWordBoundaryMatch(h.line, lowerTerms[i])) continue;
        const key = `${h.path}:${h.lineNumber}:${lowerTerms[i]}`;
        if (seen.has(key)) continue;
        seen.add(key);
        results.push({ alias: terms[i], ...h });
      }
    }
    return results;
  }

  /**
   * Full-repo pre-filter for secret-pattern anchors (see
   * SECRET_GREP_ANCHORS/PRIVATE_KEY_ANCHORS in secrets.rule.ts) - one
   * combined `git grep` call across every anchor string. Returns raw
   * candidate lines only; findFullRepoSecretMatches is what actually
   * re-applies the real regexes and decides whether any of these are genuine
   * findings, so a hit here is never reported as a secret on its own.
   */
  private async grepSecretAnchors(
    dir: string,
    timeoutMs: number,
  ): Promise<FullRepoSecretCandidate[]> {
    const raw = this.config.get<string>('ENABLE_DEEP_SECRET_GREP');
    if (raw !== undefined && raw.toLowerCase() === 'false') return [];

    const anchors = [...SECRET_GREP_ANCHORS, ...PRIVATE_KEY_ANCHORS];
    let hits: Array<{ path: string; lineNumber: number; line: string }>;
    try {
      hits = await this.runGitGrepMulti(dir, anchors, timeoutMs);
    } catch (error) {
      this.logger.warn(
        `git grep failed for secret anchors: ${(error as Error).message}`,
      );
      return [];
    }

    const results: FullRepoSecretCandidate[] = [];
    const seen = new Set<string>();
    for (const h of hits) {
      if (isExcludedPath(h.path)) continue;
      const key = `${h.path}:${h.lineNumber}`;
      if (seen.has(key)) continue;
      seen.add(key);
      results.push(h);
    }
    return results;
  }

  /** Same as runGitGrep, but ORs multiple literal patterns together in one process instead of one call per pattern - only whether a line matched ANY of them, not which one. */
  private runGitGrepMulti(
    dir: string,
    patterns: string[],
    timeoutMs: number,
  ): Promise<Array<{ path: string; lineNumber: number; line: string }>> {
    return new Promise((resolve, reject) => {
      const patternArgs = patterns.flatMap((p) => ['-e', p]);
      const proc = spawn('git', [
        '-C',
        dir,
        'grep',
        '-n',
        '-i',
        '-I',
        '-F',
        ...patternArgs,
        'HEAD',
        '--',
        '.',
        ...GREP_EXCLUDE_PATHSPECS,
      ]);
      const chunks: Buffer[] = [];
      proc.stdout?.on('data', (chunk: Buffer) => chunks.push(chunk));
      const timer = setTimeout(() => {
        proc.kill('SIGKILL');
        reject(new Error(`git grep timed out after ${timeoutMs}ms`));
      }, timeoutMs);
      proc.on('error', (err) => {
        clearTimeout(timer);
        reject(err);
      });
      proc.on('exit', (code) => {
        clearTimeout(timer);
        if (code !== 0 && code !== 1) {
          reject(new Error(`git grep exited with code ${code}`));
          return;
        }
        const out = Buffer.concat(chunks).toString('utf8');
        const results: Array<{
          path: string;
          lineNumber: number;
          line: string;
        }> = [];
        for (const rawLine of out.split('\n')) {
          if (!rawLine) continue;
          const match = /^HEAD:(.+?):(\d+):(.*)$/.exec(rawLine);
          if (!match) continue;
          results.push({
            path: match[1],
            lineNumber: Number(match[2]),
            line: match[3].trim().slice(0, 300),
          });
        }
        resolve(results);
      });
    });
  }

  private async readFileCapped(
    absPath: string,
    maxBytes: number,
  ): Promise<string | null> {
    try {
      const st = await stat(absPath);
      if (st.size > maxBytes) return null;
      const buf = await readFile(absPath);
      // Skip likely-binary files (null byte in the first chunk).
      if (buf.subarray(0, 512).includes(0)) return null;
      return buf.toString('utf8');
    } catch {
      return null;
    }
  }
}
